### ISSUE TITLE
Error downloading template: Tarball not found

### ISSUE THREAD

**Issue by 3kh0** [L4Ph/create-fuwari#1]
Logs
```
net@3kh0-pod:~$ pnpm create fuwari@latest
.../192fe541319-118                      |   +2 +
.../192fe541319-118                      | Progress: resolved 2, reused 0, downloaded 2, added 2, done
✔ Please enter the project name: fuwari
✔ Please enter the site title: Fuwari
✔ Please enter the site subtitle: Demo Site
✔ Please select the language of the site. en
✔ Install Dependencies? no
Error downloading template: Tarball not found: /home/net/.cache/giget/gh/saicaca-fuwari/main.tar.gz (offline: true)
Error: Tarball not found: /home/net/.cache/giget/gh/saicaca-fuwari/main.tar.gz (offline: true)
    at r1 (file:///home/net/.cache/pnpm/dlx/zz3vprvwvpyrd7425qssidfda4/192fe541319-118/node_modules/.pnpm/create-fuwari@0.0.6_typescript@5.6.3/node_modules/create-fuwari/dist/index.mjs:38:14007)
    at async n1 (file:///home/net/.cache/pnpm/dlx/zz3vprvwvpyrd7425qssidfda4/192fe541319-118/node_modules/.pnpm/create-fuwari@0.0.6_typescript@5.6.3/node_modules/create-fuwari/dist/index.mjs:38:14722)
    at async file:///home/net/.cache/pnpm/dlx/zz3vprvwvpyrd7425qssidfda4/192fe541319-118/node_modules/.pnpm/create-fuwari@0.0.6_typescript@5.6.3/node_modules/create-fuwari/dist/index.mjs:38:15291
node:internal/fs/promises:638
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open 'undefined/src/config.ts'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1238:14)
    at async file:///home/net/.cache/pnpm/dlx/zz3vprvwvpyrd7425qssidfda4/192fe541319-118/node_modules/.pnpm/create-fuwari@0.0.6_typescript@5.6.3/node_modules/create-fuwari/dist/index.mjs:38:15335 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'undefined/src/config.ts'
}

Node.js v22.9.0
```

**Comment by L4Ph** [comment]
Thank you for the feedback!
What about `npm create fuwari@latest`?
It could be a problem with pnpm's own behavior, so I'd like to isolate it and check!

**Comment by 3kh0** [comment]
With npm
```
net@3kh0-pod:~$ npm create fuwari@latest
Need to install the following packages:
create-fuwari@0.0.6
Ok to proceed? (y) y


> npx
> create-fuwari

✔ Please enter the project name: fuwari
✔ Please enter the site title: Fuwari
✔ Please enter the site subtitle: Demo Site
✔ Please select the language of the site. en
✔ Install Dependencies? no
Error downloading template: Tarball not found: /home/net/.cache/giget/gh/saicaca-fuwari/main.tar.gz (offline: true)
Error: Tarball not found: /home/net/.cache/giget/gh/saicaca-fuwari/main.tar.gz (offline: true)
    at r1 (file:///home/net/.npm/_npx/17c5b74d5c80770b/node_modules/create-fuwari/dist/index.mjs:38:14007)
    at async n1 (file:///home/net/.npm/_npx/17c5b74d5c80770b/node_modules/create-fuwari/dist/index.mjs:38:14722)
    at async file:///home/net/.npm/_npx/17c5b74d5c80770b/node_modules/create-fuwari/dist/index.mjs:38:15291
node:internal/fs/promises:638
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open 'undefined/src/config.ts'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1238:14)
    at async file:///home/net/.npm/_npx/17c5b74d5c80770b/node_modules/create-fuwari/dist/index.mjs:38:15335 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'undefined/src/config.ts'
}

Node.js v22.9.0
npm error code 1
npm error path /home/net
npm error command failed
npm error command sh -c create-fuwari
npm notice
npm notice New minor version of npm available! 10.8.3 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
npm error A complete log of this run can be found in: /home/net/.npm/_logs/2024-11-06T02_45_40_669Z-debug-0.log
net@3kh0-pod:~$ cat /home/net/.npm/_logs/2024-11-06T02_45_40_669Z-debug-0.log
0 verbose cli /home/net/.nvm/versions/node/v22.9.0/bin/node /home/net/.nvm/versions/node/v22.9.0/bin/npm
1 info using npm@10.8.3
2 info using node@v22.9.0
3 silly config load:file:/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/npmrc
4 silly config load:file:/home/net/.npmrc
5 silly config load:file:/home/net/.nvm/versions/node/v22.9.0/etc/npmrc
6 verbose title npm create fuwari@latest
7 verbose argv "create" "fuwari@latest"
8 verbose logfile logs-max:10 dir:/home/net/.npm/_logs/2024-11-06T02_45_40_669Z-
9 verbose logfile /home/net/.npm/_logs/2024-11-06T02_45_40_669Z-debug-0.log
10 silly logfile done cleaning log files
11 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
12 http fetch GET 200 https://registry.npmjs.org/npm 175ms
13 http fetch GET 200 https://registry.npmjs.org/create-fuwari 408ms (cache miss)
14 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
15 silly idealTree buildDeps
16 silly fetch manifest create-fuwari@0.0.6
17 silly packumentCache full:https://registry.npmjs.org/create-fuwari cache-miss
18 http fetch GET 200 https://registry.npmjs.org/create-fuwari 355ms (cache miss)
19 silly packumentCache full:https://registry.npmjs.org/create-fuwari set size:undefined disposed:false
20 silly fetch manifest typescript@^5.6.3
21 silly packumentCache full:https://registry.npmjs.org/typescript cache-miss
22 http fetch GET 200 https://registry.npmjs.org/typescript 240ms (cache miss)
23 silly packumentCache full:https://registry.npmjs.org/typescript set size:undefined disposed:false
24 silly placeDep ROOT create-fuwari@0.0.6 OK for:  want: 0.0.6
25 silly placeDep ROOT typescript@5.6.3 OK for: create-fuwari@0.0.6 want: ^5.6.3
26 silly reify moves {}
27 silly audit bulk request { 'create-fuwari': [ '0.0.6' ], typescript: [ '5.6.3' ] }
28 silly tarball no local data for typescript@https://registry.npmjs.org/typescript/-/typescript-5.6.3.tgz. Extracting by manifest.
29 silly tarball no local data for create-fuwari@https://registry.npmjs.org/create-fuwari/-/create-fuwari-0.0.6.tgz. Extracting by manifest.
30 http fetch GET 200 https://registry.npmjs.org/create-fuwari/-/create-fuwari-0.0.6.tgz 126ms (cache miss)
31 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 141ms
32 silly audit report {}
33 http fetch GET 200 https://registry.npmjs.org/typescript/-/typescript-5.6.3.tgz 238ms (cache miss)
34 verbose stack Error: command failed
34 verbose stack     at promiseSpawn (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
34 verbose stack     at spawnWithShell (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
34 verbose stack     at promiseSpawn (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
34 verbose stack     at runScriptPkg (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
34 verbose stack     at runScript (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
34 verbose stack     at run (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/libnpmexec/lib/run-script.js:48:10)
34 verbose stack     at async exec (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:298:10)
34 verbose stack     at async Init.execCreate (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/lib/commands/init.js:135:5)
34 verbose stack     at async Init.exec (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/lib/commands/init.js:44:14)
34 verbose stack     at async Npm.exec (/home/net/.nvm/versions/node/v22.9.0/lib/node_modules/npm/lib/npm.js:207:9)
35 error code 1
36 error path /home/net
37 error command failed
38 error command sh -c create-fuwari
39 verbose cwd /home/net
40 verbose os Linux 5.15.153.1-microsoft-standard-WSL2
41 verbose node v22.9.0
42 verbose npm  v10.8.3
43 notice
43 notice New minor version of npm available! 10.8.3 -> 10.9.0
43 notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
43 notice To update run: npm install -g npm@10.9.0
43 notice  { force: true, [Symbol(proc-log.meta)]: true }
44 verbose exit 1
45 verbose code 1
46 error A complete log of this run can be found in: /home/net/.npm/_logs/2024-11-06T02_45_40_669Z-debug-0.log
```

**Comment by L4Ph** [comment]
@3kh0 

There was a bug related to tsup (or rather esbuild). I've switched to rslib, so please clone and run the following commands:
```sh
pnpm i
pnpm run build
node ./bin/cli.mjs //shebang
```
and let me know the result.

**Comment by L4Ph** [comment]
This has been fixed.
I'll open an issue if the problem occurs again.
